// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button'];
    AForm: typeof import('ant-design-vue/es')['Form'];
    AFormItem: typeof import('ant-design-vue/es')['FormItem'];
    AInput: typeof import('ant-design-vue/es')['Input'];
    ALayout: typeof import('ant-design-vue/es')['Layout'];
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent'];
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter'];
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader'];
    AModal: typeof import('ant-design-vue/es')['Modal'];
    ASelect: typeof import('ant-design-vue/es')['Select'];
    GithubOutlined: typeof import('@ant-design/icons-vue')['GithubOutlined'];
    HeartFilled: typeof import('@ant-design/icons-vue')['HeartFilled'];
    MusicVisualizer: typeof import('./src/components/MusicVisualizer.vue')['default'];
    PageFooter: typeof import('./src/components/PageFooter.vue')['default'];
    PageHeader: typeof import('./src/components/PageHeader.vue')['default'];
  }
}

export {};
